INSERT INTO `Commands` (`id`, `command`, `return`, `created_at`) VALUES
	(1, '!server', 'Très cher viewers, si vous vous sentez l\'âme d\'un maître bêta testeur, vous pouvez aller sur https://trashmates.fr afin d\'accéder à un stream sans publicité, sans droit d\'auteur, avec la même qualité que sur Twitch.', '2017-08-16 22:48:21'),
	(2, '!join', 'Très cher viewers, si vous souhaitez participer à la session de jeu des TrashMates, veuillez rejoindre le groupe Steam - https://steamcommunity.com/groups/trashmates - afin que mes maîtres puissent vous ajouter à leur partie.', '2017-08-16 22:48:43'),
	(3, '!discord', 'Très cher viewers, veuillez retrouver toutes informations et activités des TrashMates sur leur serveur Discord - https://discord.io/_trashmates - ainsi que des salons vocaux afin de participer aux sessions de jeu en stream.', '2017-08-16 22:48:49'),
	(4, '!steam', 'Très cher viewers, vous pouvez rejoindre le groupe Steam de mes maîtres - http://steamcommunity.com/groups/trashmates - afin d\'être tenu informé des prochains streams, mais aussi de participer aux prochaines sessions de jeu.', '2017-08-16 22:49:06'),
	(5, '!twitter', 'Très cher viewers, maîtres TrashMates possédant un compte twitter - https://twitter.com/Trash_Mates -, il vous permettra d\'être informé de tout streams realisé par messieurs et autres anecdotes atypiques.', '2017-08-16 22:49:24'),
	(6, '!replays', 'Très cher viewers, à côté de cette chaîne Twitch, je vous propose la chaîne YouTube de maître TiCubius - https://www.youtube.com/user/TiCubiusProductions - possédant tout les vestiges enregistrés des streams passés.', '2017-08-16 22:49:43'),
	(7, '!highlights', 'Très cher viewers, à côté de cette chaîne Twitch, je vous propose la chaîne YouTube de maître Towstee - https://www.youtube.com/user/NutellasTerrorists - possédant toutes les moments d\'éclats des streams passés.', '2017-08-16 22:49:51');

INSERT INTO `Games` (`name`, `type`, `Hankiss`, `TiCubius`, `DualElite`, `Towstee`) VALUES
	('100% Orange Juice', 'coop', b'1', b'0', b'0', b'1'),
	('404Sight', 'solo', b'0', b'1', b'0', b'0'),
	('Acceleration of Suguri X-Edition', 'coop', b'1', b'0', b'0', b'0'),
	('Age of Empires II HD: The African Kingdoms', 'coop', b'0', b'0', b'0', b'1'),
	('Age of Empires II: HD Edition', 'coop', b'0', b'0', b'0', b'1'),
	('Age of Empires® III: Complete Collection', 'coop', b'0', b'0', b'0', b'1'),
	('Alien Swarm', 'coop', b'0', b'1', b'1', b'1'),
	('Alien: Isolation', 'solo', b'1', b'0', b'0', b'0'),
	('America\'s Army 3', 'coop', b'0', b'0', b'1', b'0'),
	('America\'s Army: Proving Grounds', 'coop', b'0', b'0', b'1', b'0'),
	('APB Reloaded', 'coop', b'1', b'1', b'0', b'1'),
	('Aperture Tag: The Paint Gun Testing Initiative', 'solo', b'0', b'1', b'0', b'0'),
	('Arma 2', 'coop', b'1', b'0', b'0', b'0'),
	('Arma 3', 'coop', b'0', b'0', b'1', b'0'),
	('Arma: Cold War Assault', 'coop', b'1', b'0', b'0', b'0'),
	('Aura Kingdom', 'coop', b'1', b'0', b'0', b'0'),
	('Awesomenauts', 'coop', b'0', b'1', b'0', b'1'),
	('Bastion', 'solo', b'1', b'0', b'0', b'0'),
	('Batman™: Arkham Origins', 'solo', b'0', b'0', b'1', b'0'),
	('BattleBlock Theater', 'coop', b'1', b'1', b'0', b'1'),
	('Ben and Ed', 'coop', b'0', b'0', b'0', b'1'),
	('Ben and Ed - Blood Party', 'coop', b'1', b'1', b'0', b'1'),
	('BERSERK and the Band of the Hawk', 'solo', b'1', b'0', b'0', b'0'),
	('BioShock', 'solo', b'1', b'0', b'0', b'0'),
	('BioShock 2', 'solo', b'1', b'0', b'0', b'0'),
	('BioShock 2 Remastered', 'solo', b'1', b'0', b'0', b'0'),
	('BioShock Infinite', 'solo', b'1', b'0', b'0', b'0'),
	('BioShock Remastered', 'solo', b'1', b'0', b'0', b'0'),
	('Blade Symphony', 'coop', b'1', b'0', b'0', b'1'),
	('Blocks That Matter', 'solo', b'1', b'0', b'0', b'0'),
	('Blood and Bacon', 'coop', b'1', b'1', b'0', b'1'),
	('Borderlands', 'coop', b'0', b'1', b'0', b'0'),
	('Borderlands 2', 'coop', b'1', b'1', b'1', b'1'),
	('Borderlands: The Pre-Sequel', 'coop', b'1', b'0', b'0', b'1'),
	('Brawlhalla', 'solo', b'1', b'1', b'0', b'0'),
	('Broforce', 'coop', b'0', b'0', b'0', b'1'),
	('Brütal Legend', 'solo', b'0', b'0', b'0', b'1'),
	('Call of Duty: Black Ops', 'solo', b'0', b'1', b'1', b'0'),
	('Call of Duty: Black Ops - Multiplayer', 'coop', b'0', b'1', b'1', b'0'),
	('Call of Duty: Black Ops II', 'solo', b'0', b'1', b'0', b'0'),
	('Call of Duty: Black Ops II - Multiplayer', 'coop', b'0', b'1', b'0', b'0'),
	('Call of Duty: Black Ops II - Zombies', 'coop', b'0', b'1', b'0', b'0'),
	('Call of Duty: Ghosts', 'solo', b'0', b'1', b'0', b'0'),
	('Call of Duty: Ghosts - Multiplayer', 'coop', b'0', b'1', b'0', b'0'),
	('Call of Duty: Modern Warfare 2', 'solo', b'0', b'0', b'1', b'0'),
	('Call of Duty: Modern Warfare 2 - Multiplayer', 'coop', b'0', b'0', b'1', b'0'),
	('Call of Duty: Modern Warfare 3', 'solo', b'0', b'1', b'0', b'0'),
	('Call of Duty: Modern Warfare 3 - Multiplayer', 'coop', b'0', b'1', b'0', b'0'),
	('Card Hunter', 'coop', b'0', b'0', b'1', b'0'),
	('Carpe Diem', 'solo', b'0', b'0', b'0', b'1'),
	('Castle Crashers', 'coop', b'1', b'1', b'0', b'1'),
	('Chaos on Deponia', 'solo', b'1', b'0', b'0', b'1'),
	('Child of Light', 'solo', b'1', b'0', b'0', b'0'),
	('Chivalry: Medieval Warfare', 'coop', b'1', b'1', b'1', b'1'),
	('Choice Chamber', 'solo', b'0', b'1', b'0', b'1'),
	('Clicker Heroes', 'solo', b'0', b'1', b'0', b'0'),
	('Clustertruck', 'solo', b'0', b'0', b'0', b'1'),
	('Codename Gordon', 'solo', b'0', b'0', b'0', b'1'),
	('Contrast', 'solo', b'0', b'0', b'0', b'1'),
	('Counter-Strike: Global Offensive', 'coop', b'1', b'1', b'1', b'1'),
	('Counter-Strike: Source', 'coop', b'1', b'0', b'1', b'1'),
	('DARK SOULS™ II', 'solo', b'0', b'0', b'1', b'0'),
	('Day of Defeat: Source', 'coop', b'0', b'0', b'1', b'0'),
	('DayZ', 'coop', b'1', b'0', b'0', b'0'),
	('Dead by Daylight', 'coop', b'0', b'0', b'0', b'1'),
	('Dead Island: Epidemic', 'coop', b'1', b'0', b'0', b'1'),
	('Dead Rising 2', 'coop', b'1', b'0', b'0', b'1'),
	('Dead Rising 3', 'coop', b'1', b'0', b'0', b'1'),
	('Deadly 30', 'solo', b'1', b'0', b'0', b'0'),
	('Deponia', 'solo', b'1', b'0', b'0', b'1'),
	('DiRT 3 Complete Edition', 'coop', b'0', b'1', b'0', b'1'),
	('DiRT Showdown', 'coop', b'0', b'1', b'0', b'1'),
	('Dishonored', 'solo', b'0', b'0', b'1', b'0'),
	('Dishonored 2', 'solo', b'0', b'0', b'1', b'1'),
	('Don\'t Starve', 'solo', b'1', b'0', b'0', b'1'),
	('Don\'t Starve Together', 'coop', b'1', b'0', b'0', b'1'),
	('DOOM', 'solo', b'0', b'0', b'1', b'1'),
	('DOOM II: Hell on Earth', 'solo', b'0', b'0', b'1', b'0'),
	('Dota 2', 'coop', b'0', b'0', b'1', b'1'),
	('Dota 2 Test', 'coop', b'0', b'0', b'0', b'1'),
	('Double Action: Boogaloo', 'coop', b'0', b'1', b'0', b'1'),
	('Dragon Nest Europe', 'coop', b'0', b'1', b'0', b'0'),
	('Dragon Saga', 'coop', b'1', b'0', b'0', b'0'),
	('Duck Game', 'coop', b'1', b'1', b'0', b'1'),
	('Duelyst', 'coop', b'0', b'1', b'0', b'0'),
	('Dungeon Defenders', 'coop', b'1', b'0', b'0', b'0'),
	('Dungeon Defenders II', 'coop', b'1', b'1', b'0', b'1'),
	('Dungeon Siege III', 'coop', b'0', b'1', b'0', b'0'),
	('Dust: An Elysian Tail', 'solo', b'1', b'0', b'0', b'0'),
	('Dustforce', 'solo', b'1', b'0', b'0', b'0'),
	('E.Y.E: Divine Cybermancy', 'solo', b'1', b'0', b'0', b'1'),
	('Emily is Away', 'solo', b'0', b'0', b'0', b'1'),
	('Enter the Gungeon', 'coop', b'1', b'0', b'0', b'0'),
	('Eon Altar', 'coop', b'0', b'1', b'0', b'0'),
	('Eryi\'s Action', 'solo', b'1', b'0', b'0', b'0'),
	('Eternal Silence', 'coop', b'0', b'0', b'1', b'0'),
	('Evolve Stage 2', 'coop', b'1', b'1', b'1', b'1'),
	('FaceRig', 'solo', b'0', b'0', b'0', b'1'),
	('Fallout 4', 'coop', b'1', b'0', b'0', b'0'),
	('Final DOOM', 'solo', b'0', b'0', b'1', b'0'),
	('FINAL FANTASY XIV Online', 'coop', b'1', b'0', b'0', b'0'),
	('Fistful of Frags', 'coop', b'0', b'1', b'0', b'0'),
	('Five Nights at Freddy\'s', 'coop', b'1', b'0', b'0', b'0'),
	('Five Nights at Freddy\'s 2', 'coop', b'1', b'0', b'0', b'0'),
	('Five Nights at Freddy\'s 3', 'coop', b'1', b'0', b'0', b'0'),
	('Fractured Space', 'coop', b'0', b'1', b'0', b'0'),
	('Gang Beasts', 'coop', b'1', b'0', b'0', b'1'),
	('Garry\'s Mod', 'coop', b'1', b'1', b'1', b'1'),
	('Ghost in the Shell: Stand Alone Complex - First Assault Online', 'coop', b'0', b'1', b'0', b'1'),
	('Goat Simulator', 'solo', b'1', b'0', b'0', b'0'),
	('Gone Home', 'solo', b'1', b'0', b'0', b'1'),
	('Goodbye Deponia', 'solo', b'1', b'0', b'0', b'1'),
	('Grand Theft Auto IV', 'coop', b'1', b'1', b'0', b'1'),
	('Grand Theft Auto V', 'coop', b'1', b'0', b'0', b'0'),
	('Grand Theft Auto: Episodes from Liberty City', 'coop', b'0', b'0', b'0', b'1'),
	('Grand Theft Auto: San Andreas', 'coop', b'1', b'0', b'0', b'0'),
	('GundeadliGne', 'coop', b'1', b'0', b'0', b'0'),
	('Gundemonium Recollection', 'coop', b'1', b'0', b'0', b'0'),
	('Hacknet', 'solo', b'0', b'0', b'0', b'1'),
	('Half dead', 'coop', b'1', b'0', b'0', b'0'),
	('Half-Life', 'solo', b'0', b'1', b'0', b'0'),
	('Half-Life 2', 'solo', b'1', b'1', b'1', b'1'),
	('Half-Life 2: Deathmatch', 'coop', b'0', b'1', b'1', b'0'),
	('Half-Life 2: Episode One', 'solo', b'0', b'1', b'1', b'0'),
	('Half-Life 2: Episode Two', 'solo', b'0', b'1', b'1', b'0'),
	('Half-Life 2: Lost Coast', 'solo', b'1', b'1', b'1', b'1'),
	('Half-Life Deathmatch: Source', 'coop', b'0', b'1', b'1', b'0'),
	('Half-Life: Blue Shift', 'solo', b'0', b'1', b'0', b'0'),
	('Half-Life: Opposing Force', 'solo', b'0', b'1', b'0', b'0'),
	('Half-Life: Source', 'solo', b'0', b'1', b'0', b'0'),
	('Haunted Memories', 'solo', b'0', b'0', b'0', b'1'),
	('Hell Yeah!', 'solo', b'0', b'1', b'0', b'0'),
	('HELLDIVERS™', 'coop', b'0', b'0', b'1', b'0'),
	('Hero Siege', 'coop', b'1', b'0', b'0', b'0'),
	('HIT', 'solo', b'0', b'0', b'0', b'1'),
	('Hitogata Happa', 'solo', b'1', b'0', b'0', b'0'),
	('Hotline Miami', 'solo', b'1', b'0', b'0', b'0'),
	('Hotline Miami 2: Wrong Number', 'solo', b'1', b'0', b'0', b'0'),
	('Hotline Miami 2: Wrong Number Digital Comic', 'solo', b'1', b'0', b'0', b'0'),
	('ibb & obb', 'coop', b'0', b'0', b'0', b'1'),
	('Insurgency', 'coop', b'0', b'0', b'1', b'0'),
	('Intrusion 2', 'solo', b'1', b'0', b'0', b'0'),
	('Jet Set Radio', 'solo', b'0', b'1', b'0', b'0'),
	('Jotun', 'solo', b'0', b'0', b'1', b'0'),
	('Just Cause 3', 'solo', b'0', b'1', b'0', b'1'),
	('Killing Floor', 'coop', b'1', b'1', b'1', b'1'),
	('Killing Floor - Toy Master', 'coop', b'1', b'0', b'0', b'1'),
	('Killing Floor 2', 'coop', b'1', b'1', b'0', b'1'),
	('Killing Floor 2 - SDK', 'coop', b'1', b'1', b'0', b'1'),
	('Killing Floor Mod: Defence Alliance 2', 'coop', b'1', b'1', b'1', b'1'),
	('King Arthur\'s Gold', 'coop', b'1', b'1', b'0', b'0'),
	('KROSMAGA', 'coop', b'1', b'1', b'0', b'0'),
	('Left 4 Dead 2', 'coop', b'1', b'1', b'1', b'1'),
	('Left 4 Dead 2 Beta', 'coop', b'1', b'1', b'0', b'1'),
	('Lethal League', 'coop', b'1', b'0', b'0', b'1'),
	('Life is Strange™', 'solo', b'1', b'1', b'0', b'0'),
	('Loadout', 'coop', b'0', b'1', b'0', b'1'),
	('Lucius', 'solo', b'0', b'0', b'0', b'1'),
	('Magicite', 'coop', b'1', b'0', b'0', b'0'),
	('Magicka', 'coop', b'1', b'0', b'1', b'0'),
	('Master Levels for DOOM II', 'solo', b'0', b'0', b'1', b'0'),
	('Max Payne', 'solo', b'0', b'0', b'1', b'0'),
	('Max Payne 2: The Fall of Max Payne', 'solo', b'0', b'0', b'1', b'0'),
	('Max Payne 3', 'solo', b'0', b'0', b'1', b'0'),
	('Medieval II: Total War', 'coop', b'0', b'0', b'1', b'0'),
	('Melody\'s Escape', 'solo', b'1', b'0', b'0', b'0'),
	('METAL GEAR SOLID V: THE PHANTOM PAIN', 'solo', b'1', b'0', b'1', b'0'),
	('METAL SLUG X', 'coop', b'0', b'0', b'0', b'1'),
	('Metaverse Construction Kit', 'solo', b'0', b'1', b'0', b'0'),
	('Metro 2033', 'solo', b'0', b'1', b'0', b'1'),
	('MicroVolts Surge', 'coop', b'1', b'0', b'0', b'0'),
	('Mirror\'s Edge', 'solo', b'0', b'1', b'0', b'0'),
	('Modular Combat', 'solo', b'0', b'0', b'0', b'1'),
	('Momodora: Reverie Under the Moonlight', 'solo', b'1', b'0', b'0', b'0'),
	('Monaco', 'coop', b'1', b'1', b'0', b'1'),
	('Mortal Kombat X', 'coop', b'0', b'0', b'1', b'0'),
	('Mount Your Friends', 'coop', b'1', b'1', b'0', b'1'),
	('Mr.President!', 'coop', b'0', b'0', b'0', b'1'),
	('Neverwinter', 'coop', b'0', b'1', b'0', b'0'),
	('Nights of Azure', 'solo', b'1', b'0', b'0', b'0'),
	('No More Room in Hell', 'coop', b'0', b'0', b'1', b'0'),
	('Noitu Love 2 Devolution', 'solo', b'1', b'0', b'0', b'0'),
	('Nuclear Throne', 'solo', b'1', b'0', b'0', b'0'),
	('Only If', 'solo', b'0', b'0', b'0', b'1'),
	('Outland', 'coop', b'1', b'1', b'0', b'1'),
	('Outlast', 'solo', b'0', b'0', b'0', b'1'),
	('Paladins', 'coop', b'0', b'1', b'1', b'1'),
	('Paladins - Public Test', 'coop', b'0', b'1', b'0', b'1'),
	('Path of Exile', 'coop', b'0', b'0', b'1', b'0'),
	('PAYDAY 2', 'coop', b'1', b'1', b'1', b'1'),
	('PAYDAY: The Heist', 'coop', b'1', b'1', b'1', b'1'),
	('Pit People', 'solo', b'1', b'0', b'0', b'0'),
	('Plague Inc: Evolved', 'coop', b'0', b'0', b'1', b'1'),
	('Planetary Annihilation', 'coop', b'1', b'0', b'0', b'1'),
	('Planetary Annihilation: TITANS', 'coop', b'0', b'0', b'0', b'1'),
	('PlanetSide 2', 'coop', b'0', b'1', b'1', b'1'),
	('Poker Night 2', 'solo', b'1', b'0', b'0', b'0'),
	('Poker Night at the Inventory', 'solo', b'1', b'1', b'0', b'1'),
	('Pool Nation FX', 'solo', b'0', b'0', b'0', b'1'),
	('Portal 2', 'coop', b'1', b'1', b'1', b'1'),
	('Portal Knights', 'coop', b'1', b'0', b'0', b'0'),
	('Portal Stories: Mel', 'solo', b'0', b'1', b'0', b'0'),
	('POSTAL 2', 'coop', b'0', b'0', b'0', b'1'),
	('Primal Carnage: Extinction', 'coop', b'0', b'1', b'0', b'0'),
	('Q.U.B.E.', 'solo', b'1', b'0', b'0', b'1'),
	('Q.U.B.E: Director\'s Cut', 'solo', b'1', b'0', b'0', b'1'),
	('Quake Live', 'coop', b'0', b'1', b'0', b'0'),
	('Race The Sun', 'solo', b'0', b'0', b'0', b'1'),
	('RAGE', 'coop', b'0', b'0', b'0', b'1'),
	('Ravaged Zombie Apocalypse', 'coop', b'0', b'0', b'1', b'0'),
	('Red Faction: Guerrilla Steam Edition', 'solo', b'0', b'0', b'1', b'0'),
	('Reveal The Deep', 'solo', b'0', b'0', b'0', b'1'),
	('Rising Storm/Red Orchestra 2 Multiplayer', 'coop', b'0', b'0', b'1', b'0'),
	('Risk of Rain', 'coop', b'1', b'1', b'0', b'0'),
	('Robocraft', 'coop', b'0', b'0', b'0', b'1'),
	('Rocket League', 'coop', b'0', b'1', b'0', b'1'),
	('Rogue Legacy', 'solo', b'1', b'0', b'0', b'0'),
	('Royal Quest', 'coop', b'0', b'1', b'0', b'0'),
	('Rust', 'solo', b'1', b'0', b'0', b'1'),
	('RWBY: Grimm Eclipse', 'coop', b'1', b'0', b'0', b'0'),
	('Saints Row 2', 'coop', b'0', b'0', b'1', b'0'),
	('Saints Row IV', 'coop', b'0', b'0', b'0', b'1'),
	('Saints Row: Gat out of Hell', 'coop', b'0', b'0', b'0', b'1'),
	('Saints Row: The Third', 'coop', b'0', b'1', b'0', b'0'),
	('Sakura Clicker', 'solo', b'1', b'0', b'0', b'1'),
	('Sam & Max 104: Abe Lincoln Must Die!', 'solo', b'0', b'0', b'0', b'1'),
	('Scrap Mechanic', 'coop', b'0', b'0', b'0', b'1'),
	('Secrets of Grindea', 'coop', b'1', b'0', b'0', b'0'),
	('SEGA Mega Drive & Genesis Classics', 'solo', b'0', b'1', b'0', b'0'),
	('Serious Sam 3: BFE', 'coop', b'1', b'1', b'0', b'1'),
	('Serious Sam Fusion 2017 (beta)', 'coop', b'1', b'1', b'0', b'1'),
	('Serious Sam HD: The Second Encounter', 'coop', b'0', b'0', b'0', b'1'),
	('Shadow Warrior', 'solo', b'0', b'0', b'0', b'1'),
	('Shadowgrounds', 'solo', b'0', b'0', b'0', b'1'),
	('Shadowgrounds: Survivor', 'solo', b'0', b'0', b'0', b'1'),
	('Shadwen', 'solo', b'0', b'0', b'0', b'1'),
	('Shovel Knight: Treasure Trove', 'solo', b'1', b'0', b'0', b'0'),
	('Sid Meier\'s Civilization V', 'coop', b'0', b'0', b'1', b'0'),
	('Sir, You Are Being Hunted', 'coop', b'1', b'0', b'0', b'1'),
	('Skullgirls', 'coop', b'1', b'0', b'0', b'1'),
	('Skullgirls ∞Endless Beta∞', 'coop', b'1', b'0', b'0', b'0'),
	('Skyrim Script Extender (SKSE)', 'solo', b'0', b'0', b'0', b'1'),
	('Source Filmmaker', 'solo', b'1', b'1', b'0', b'1'),
	('Source SDK', 'solo', b'0', b'0', b'0', b'1'),
	('SpeedRunners', 'coop', b'1', b'1', b'0', b'1'),
	('Spore', 'solo', b'0', b'0', b'0', b'1'),
	('Spore: Creepy & Cute Parts Pack', 'solo', b'0', b'0', b'0', b'1'),
	('Spore: Galactic Adventures', 'solo', b'0', b'0', b'0', b'1'),
	('Star Conflict', 'coop', b'0', b'0', b'1', b'0'),
	('STAR WARS™ Republic Commando', 'solo', b'0', b'0', b'1', b'0'),
	('Starbound', 'coop', b'1', b'1', b'0', b'1'),
	('Starbound - Unstable', 'coop', b'1', b'1', b'0', b'1'),
	('Streamline', 'coop', b'0', b'1', b'0', b'0'),
	('Street Fighter V', 'coop', b'0', b'0', b'1', b'0'),
	('Strike Vector', 'coop', b'0', b'0', b'0', b'1'),
	('Styx: Shards of Darkness', 'coop', b'1', b'0', b'0', b'1'),
	('Suguri', 'solo', b'1', b'0', b'0', b'0'),
	('Sven Co-op', 'coop', b'0', b'1', b'0', b'0'),
	('Synergy', 'coop', b'1', b'1', b'1', b'1'),
	('Tabletop Simulator', 'coop', b'1', b'0', b'0', b'1'),
	('Tales of Berseria', 'solo', b'1', b'0', b'0', b'0'),
	('Tales of Symphonia', 'solo', b'1', b'0', b'0', b'0'),
	('Tales of Zestiria', 'solo', b'1', b'0', b'0', b'0'),
	('Team Fortress 2', 'coop', b'1', b'1', b'1', b'1'),
	('Team Fortress Classic', 'coop', b'0', b'1', b'0', b'0'),
	('Terraria', 'coop', b'1', b'1', b'0', b'1'),
	('The Binding of Isaac', 'coop', b'1', b'0', b'0', b'0'),
	('The Binding of Isaac: Rebirth', 'coop', b'1', b'0', b'0', b'0'),
	('The Deer God', 'solo', b'0', b'0', b'0', b'1'),
	('The Elder Scrolls Online: Tamriel Unlimited', 'coop', b'1', b'0', b'0', b'1'),
	('The Elder Scrolls V: Skyrim', 'solo', b'1', b'0', b'1', b'1'),
	('The Elder Scrolls V: Skyrim Special Edition', 'solo', b'1', b'0', b'0', b'1'),
	('The Elder Scrolls: Legends', 'solo', b'1', b'0', b'0', b'0'),
	('The Escapists', 'solo', b'0', b'1', b'0', b'0'),
	('The Ultimate DOOM', 'solo', b'0', b'0', b'1', b'0'),
	('The Way of Life Free Edition', 'solo', b'0', b'0', b'0', b'1'),
	('The Witcher: Enhanced Edition', 'solo', b'0', b'1', b'0', b'0'),
	('theHunter Classic', 'solo', b'0', b'0', b'0', b'1'),
	('They Bleed Pixels', 'solo', b'1', b'0', b'0', b'0'),
	('Thief', 'solo', b'0', b'0', b'1', b'0'),
	('Tom Clancy\'s Ghost Recon Phantoms - EU', 'coop', b'0', b'0', b'0', b'1'),
	('Tom Clancy\'s Rainbow Six Siege', 'coop', b'0', b'0', b'1', b'0'),
	('Tom Clancy\'s Splinter Cell Blacklist', 'coop', b'0', b'0', b'0', b'1'),
	('Toribash', 'coop', b'0', b'1', b'1', b'0'),
	('TOXIKK', 'coop', b'0', b'0', b'0', b'1'),
	('TrackMania² Stadium', 'coop', b'0', b'0', b'1', b'0'),
	('Tricky Towers', 'coop', b'0', b'1', b'0', b'1'),
	('Trine', 'coop', b'0', b'0', b'0', b'1'),
	('Trine 2', 'coop', b'0', b'0', b'0', b'1'),
	('Trine 3: The Artifacts of Power', 'coop', b'0', b'0', b'0', b'1'),
	('Tropico 4', 'coop', b'0', b'0', b'1', b'0'),
	('Undertale', 'solo', b'1', b'0', b'0', b'0'),
	('Unturned', 'coop', b'0', b'1', b'0', b'1'),
	('VA-11 Hall-A: Cyberpunk Bartender Action', 'solo', b'1', b'0', b'0', b'0'),
	('Viscera Cleanup Detail: Shadow Warrior', 'coop', b'0', b'0', b'0', b'1'),
	('Warface', 'coop', b'0', b'1', b'0', b'0'),
	('Warframe', 'coop', b'1', b'1', b'1', b'1'),
	('Wargame: Red Dragon', 'coop', b'0', b'0', b'1', b'0'),
	('Warhammer 40,000: Dawn of War - Dark Crusade', 'coop', b'0', b'0', b'0', b'1'),
	('Warhammer 40,000: Dawn of War - Soulstorm', 'coop', b'0', b'0', b'0', b'1'),
	('Warhammer 40,000: Eternal Crusade', 'coop', b'0', b'0', b'1', b'0'),
	('Watch_Dogs', 'solo', b'1', b'0', b'0', b'0'),
	('What The Box?', 'coop', b'1', b'1', b'0', b'1'),
	('Wings of Vi', 'solo', b'1', b'0', b'0', b'0'),
	('Wolfenstein: The New Order', 'solo', b'1', b'0', b'0', b'0'),
	('Wolfenstein: The Old Blood', 'solo', b'0', b'0', b'1', b'0'),
	('Worms Revolution', 'coop', b'0', b'1', b'0', b'1'),
	('XCOM 2', 'solo', b'0', b'0', b'1', b'0'),
	('XCOM: Enemy Unknown', 'solo', b'0', b'0', b'1', b'0'),
	('Xenonauts', 'solo', b'1', b'0', b'0', b'1');
